# Generated by Django 5.2.15 on 2026-06-24 17:27

import django.db.models.deletion
import lasoo.checklist
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LasooOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lasoo_invoice_number', models.CharField(blank=True, default='', max_length=255)),
                ('external_order_key', models.CharField(blank=True, default='', max_length=255)),
                ('customer_info_json', models.JSONField(blank=True, null=True)),
                ('line_items_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('sent', 'Sent'), ('shipping_submitted', 'Shipping Submitted'), ('shipping_complete', 'Shipping Complete')], default='new', max_length=30)),
                ('shipping_status', models.CharField(default='pending', max_length=30)),
                ('total_amount_cents', models.IntegerField(blank=True, null=True)),
                ('lasoo_response_json', models.JSONField(blank=True, null=True)),
                ('environment', models.CharField(choices=[('staging', 'Staging'), ('production', 'Production')], default='staging', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LasooShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=255)),
                ('carrier', models.CharField(blank=True, default='', max_length=255)),
                ('tracking_url', models.URLField(blank=True, default='')),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('lasoo_request_json', models.JSONField(blank=True, null=True)),
                ('lasoo_response_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='lasoo.lasooorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_name', models.CharField(default='lasoo', max_length=50)),
                ('store_name', models.CharField(max_length=255)),
                ('retailer_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('environment', models.CharField(choices=[('staging', 'Staging'), ('production', 'Production')], default='staging', max_length=20)),
                ('active_auth_key_type', models.CharField(choices=[('staging', 'Staging'), ('production', 'Production')], default='staging', max_length=20)),
                ('staging_base_url', models.URLField(blank=True, default='')),
                ('production_base_url', models.URLField(blank=True, default='')),
                ('endpoints_json', models.JSONField(blank=True, default=dict)),
                ('staging_auth_key_encrypted', models.TextField(blank=True, default='')),
                ('production_auth_key_encrypted', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Not Connected'), ('connected_staging', 'Connected to Staging'), ('staging_completed', 'Staging Completed'), ('connected_production', 'Connected to Production'), ('failed', 'Failed'), ('disconnected', 'Disconnected')], default='pending', max_length=30)),
                ('staging_checklist_json', models.JSONField(default=lasoo.checklist.default_checklist)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lasooorder',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='lasoo.marketplaceconnection'),
        ),
        migrations.CreateModel(
            name='LasooListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_product_key', models.CharField(max_length=255)),
                ('external_variant_key', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=500)),
                ('sku', models.CharField(max_length=255)),
                ('barcode', models.CharField(blank=True, default='', max_length=255)),
                ('image_urls', models.TextField()),
                ('inventory', models.IntegerField(default=0)),
                ('infinite_quantity', models.BooleanField(default=False)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_price_cents', models.IntegerField(default=0)),
                ('sale_price_cents', models.IntegerField(default=0)),
                ('external_data_object_json', models.TextField(blank=True, default='')),
                ('environment', models.CharField(choices=[('staging', 'Staging'), ('production', 'Production')], default='staging', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validation_failed', 'Validation Failed'), ('ready', 'Ready to Upload'), ('uploaded_staging', 'Uploaded to Staging'), ('mapped', 'Mapped by Lasoo'), ('uploaded_production', 'Uploaded to Production'), ('failed', 'Failed')], default='draft', max_length=30)),
                ('validation_errors_json', models.JSONField(blank=True, null=True)),
                ('lasoo_request_json', models.JSONField(blank=True, null=True)),
                ('lasoo_response_json', models.JSONField(blank=True, null=True)),
                ('last_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='lasoo.marketplaceconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='marketplaceconnection',
            index=models.Index(fields=['user', 'marketplace_name'], name='lasoo_marke_user_id_792a62_idx'),
        ),
        migrations.AddConstraint(
            model_name='lasooorder',
            constraint=models.UniqueConstraint(fields=('connection', 'external_order_key', 'environment'), name='uniq_order_per_connection_env'),
        ),
        migrations.AddIndex(
            model_name='lasoolisting',
            index=models.Index(fields=['user', 'status'], name='lasoo_lasoo_user_id_e73cc7_idx'),
        ),
        migrations.AddConstraint(
            model_name='lasoolisting',
            constraint=models.UniqueConstraint(fields=('connection', 'external_variant_key', 'environment'), name='uniq_variant_per_connection_env'),
        ),
    ]
